name: Ejercicio 1

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo personalizado
        run: echo "Hola, mi nombre es Juan Morel"

      - name: Mostrar fecha y hora
        run: date

      - name: Mostrar sistema operativo
        run: echo "Sistema operativo: $RUNNER_OS" 